import React from "react";
import Faq from "@/views/faq/page";

export const metadata = {
  title: "صفحه سوالات متداول",
  description: "Generated by create next app",
};

function faq() {
  return <Faq />;
}

export default faq;
