import Faq from "@/views/faq/Faq";
import React from "react";

export const metadata = {
  title: "صفحه سوالات متداول",
  description: "Generated by create next app",
};

function faq() {
  return (
    <div>
      <Faq />
    </div>
  );
}

export default faq;
