import React from "react";

export const metadata = {
  title: "صفحه سوالات متداول",
  description: "Generated by create next app",
};

function Faq() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی سوالات متداول
    </div>
  );
}

export default Faq;
