import Aboutus from "@/views/about-us/Aboutus";
import React from "react";

export const metadata = {
  title: "صفحه درباره ما",
  description: "Generated by create next app",
};

function aboutus() {
  return (
    <div>
      <Aboutus />
    </div>
  );
}

export default aboutus;
