import React from "react";

export const metadata = {
  title: "صفحه درباره ما",
  description: "Generated by create next app",
};

function Aboutus() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی درباره ی ما
    </div>
  );
}

export default Aboutus;
