import React from "react";

export const metadata = {
  title: "صفحه همکاری با پادباکس",
  description: "Generated by create next app",
};

function Workwith() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی همکاری با ما
    </div>
  );
}

export default Workwith;
