import React from "react";
import Workwith from "@/views/work-with-us/page";

export const metadata = {
  title: "صفحه همکاری با پادباکس",
  description: "Generated by create next app",
};

function workwith() {
  return <Workwith />;
}

export default workwith;
