import React from "react";
import Job from "@/views/job/Job";

export const metadata = {
  title: "صفحه فرصت های شغلی",
  description: "Generated by create next app",
};

function job() {
  return <Job />;
}

export default job;
