import React from "react";
import Contact from "@/views/contact/Contact";

export const metadata = {
  title: "صفحه تماس با ما",
  description: "Generated by create next app",
};

function contact() {
  return (
    <div>
      <Contact />
    </div>
  );
}

export default contact;
