import React from "react";

export const metadata = {
  title: "صفحه فرصت های شغلی",
  description: "Generated by create next app",
};

function Job() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی فرصت های شغلی
    </div>
  );
}

export default Job;
