import Home from "@/components/Home/Home";
import "../assets/css/globals.css";

export const metadata = {
  title: "پادباکس",
  description: "Generated by create next app",
};

export default function home() {
  return (
    <div>
      <Home />
    </div>
  );
}
