import Home from "@/app/component/home";
import "./globals.css";

export const metadata = {
  title: "پادباکس",
  description: "Generated by create next app",
};

export default function home() {
  return (
    <div>
      <Home />
    </div>
  );
}
