import React from "react";

export const metadata = {
  title: "صفحه تماس با ما",
  description: "Generated by create next app",
};

function Contact() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی تماس با ما
    </div>
  );
}

export default Contact;
