import React from "react";
import Blog from "@/views/blog/Blog";

export const metadata = {
  title: "بلاگ",
  description: "Generated by create next app",
};

function blog() {
  return <Blog />;
}

export default blog;
