import React from "react";

export const metadata = {
  title: "بلاگ",
  description: "Generated by create next app",
};

function Blog() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی وبلاگ
    </div>
  );
}

export default Blog;
