import React from "react";
import Terms from "@/views/terms-and-conditions/Terms";

export const metadata = {
  title: "قوانین و مقررات پادباکس",
  description: "Generated by create next app",
};

function terms() {
  return <Terms />;
}

export default terms;
