import React from "react";

export const metadata = {
  title: "قوانین و مقررات پادباکس",
  description: "Generated by create next app",
};

function Terms() {
  return (
    <div className="flex justify-center text-b-from p-10 w-full h-screen">
      صفحه ی قوانین و مقررات
    </div>
  );
}

export default Terms;
